[graph]
all-features = true

[advisories]
unmaintained = "workspace"
ignore = [
]

[bans]
multiple-versions = "deny"
wildcards = "deny"
allow-wildcard-paths = true

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
confidence-threshold = 0.95
allow = [
    "Apache-2.0",
    "MIT",
]
exceptions = [
    # Each entry is the crate and version constraint, and its specific allow
    # list
    { crate = "unicode-ident", allow = ["Unicode-3.0"] },
]
